/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gym;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronak
 */
public class memdetails extends javax.swing.JFrame {

    /**
     * Creates new form memdetails
     */
    public memdetails() {
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
       jButton4.setVisible(false);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/gym logo.jpg"))); // NOI18N

        jLabel2.setText("MEMBERSHIP ID");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setName("scroll"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "LAST NAME", "ADDRESS", "EMAIL ID", "GENDER", "CONTACT NO", "AGE", "MEMBERSHIP TYPE", "DATE OF JOINING", "EXPIRIY DATE", "FEES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("DELETE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("RESET");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton4.setText("RENEW MEMBERSHIP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(487, 487, 487)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(504, 504, 504)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 395, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton8)
                    .addComponent(jButton2)
                    .addComponent(jButton7))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(131, 131, 131))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
        new homepage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jTextField1.getText().length()==0)
           JOptionPane.showMessageDialog(null,"ENTER MEMBERSHIP ID");
       else{
           String[] columnNames={"MEMBER_ID","FIRSTNAME","LASTNAME","ADDRESS","EMAILID","GENDER","CONTACTNO","AGE","MEMBERSHIPTYPE","DATEOFJOINING","EXPIRYDATE","FEES"};
           DefaultTableModel model = new DefaultTableModel();
         model.setColumnIdentifiers(columnNames);
         jTable1.setModel(model);
         jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_ALL_COLUMNS);
jTable1.setFillsViewportHeight(true);

try{
    Connection con; 
    con=DriverManager.getConnection("jdbc:derby://localhost:1527/registration","nbuser","nbuser");
    String sql = "select * from NBUSER.MEMBER where MEMBER_ID = '"+jTextField1.getText()+"'";
PreparedStatement ps = con.prepareStatement(sql);
ResultSet rs = ps.executeQuery();
int i =0;
if(rs.next())
{
String MEMBER_ID="";
String FIRSTNAME="";
String LASTNAME="";
String ADDRESS="";
String EMAILID="";
String GENDER="";
String CONTACTNO="";
String AGE="";
String MEMBERSHIPTYPE="";
String DATEOFJOINING="";
String EXPIRYDATE="";
String FEES="";
MEMBER_ID= rs.getString("MEMBER_ID");
FIRSTNAME= rs.getString("FIRSTNAME");
LASTNAME= rs.getString("LASTNAME");
ADDRESS = rs.getString("ADDRESS");
EMAILID = rs.getString("EMAILID");
GENDER = rs.getString("GENDER");
CONTACTNO = rs.getString("PNO");
AGE= rs.getString("AGE");
MEMBERSHIPTYPE = rs.getString("MEMBERSHIPTYPE");
DATEOFJOINING = rs.getString("JOININGDATE");
EXPIRYDATE = rs.getString("EXPIRYDATE");
FEES=rs.getString("FEES");
model.addRow(new Object[]{MEMBER_ID,FIRSTNAME,LASTNAME,ADDRESS,EMAILID,GENDER,CONTACTNO,AGE,MEMBERSHIPTYPE,DATEOFJOINING,EXPIRYDATE,FEES});
i++; 
jButton4.setVisible(true);
}
if(i <1)
{
JOptionPane.showMessageDialog(null, "No Record Found");
}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
       

this.setVisible(true);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      if(jTextField1.getText().length()==0)
           JOptionPane.showMessageDialog(null,"ENTER MEMBERSHIP ID");
      else{ 
          try{
    Connection con; 
    con=DriverManager.getConnection("jdbc:derby://localhost:1527/registration","nbuser","nbuser");
    String sql = "delete from NBUSER.MEMBER where MEMBER_ID = '"+jTextField1.getText()+"'";
PreparedStatement ps = con.prepareStatement(sql);
     int r=JOptionPane.showConfirmDialog(null, "Are you Sure u want to delete?","Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
     if(r==JOptionPane.YES_OPTION)
     {
       ps.executeUpdate();
      JOptionPane.showMessageDialog(null,"Record deleted"); 
     }
      }
      catch(Exception e)
      {
              
       }}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
jTextField1.setText("");
 DefaultTableModel model = new DefaultTableModel();
         model.setRowCount(0);
         jTable1.setModel(model);

           // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(jTextField1.getText().length()==0)
      {
          JOptionPane.showMessageDialog(null,"ENTER MEMBERSHIP ID");
      }  
      else{
             try{
    Connection con; 
    con=DriverManager.getConnection("jdbc:derby://localhost:1527/registration","nbuser","nbuser");
    String sql = "select * from NBUSER.MEMBER where MEMBER_ID = '"+jTextField1.getText()+"'";
PreparedStatement ps = con.prepareStatement(sql);
ResultSet rs = ps.executeQuery();
int i =0;
if(rs.next())
{
String MEMBER_ID="";
String FIRSTNAME="";
String LASTNAME="";
String ADDRESS="";
String EMAILID="";
String GENDER="";
String CONTACTNO="";
String AGE="";
String MEMBERSHIPTYPE="";
String DATEOFJOINING="";
String EXPIRYDATE="";
String FEES="";
MEMBER_ID= rs.getString("MEMBER_ID");
FIRSTNAME= rs.getString("FIRSTNAME");
LASTNAME= rs.getString("LASTNAME");
ADDRESS = rs.getString("ADDRESS");
EMAILID = rs.getString("EMAILID");
GENDER = rs.getString("GENDER");
CONTACTNO = rs.getString("PNO");
AGE= rs.getString("AGE");
MEMBERSHIPTYPE = rs.getString("MEMBERSHIPTYPE");
DATEOFJOINING = rs.getString("JOININGDATE");
EXPIRYDATE = rs.getString("EXPIRYDATE");
FEES=rs.getString("FEES");
updatemember um=new updatemember(MEMBER_ID,FIRSTNAME,LASTNAME,ADDRESS,EMAILID,GENDER,CONTACTNO,AGE,MEMBERSHIPTYPE,DATEOFJOINING,EXPIRYDATE,FEES);
      um.setVisible(true);
      
}
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null, e);
      }
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
             if(jTextField1.getText().length()==0)
      {
          JOptionPane.showMessageDialog(null,"ENTER MEMBERSHIP ID");
      }  
      else{
             try{
    Connection con; 
    con=DriverManager.getConnection("jdbc:derby://localhost:1527/registration","nbuser","nbuser");
    String sql = "select * from NBUSER.MEMBER where MEMBER_ID = '"+jTextField1.getText()+"'";
PreparedStatement ps = con.prepareStatement(sql);
ResultSet rs = ps.executeQuery();
int i =0;
if(rs.next())
{
String MEMBER_ID="";
String FIRSTNAME="";
String LASTNAME="";
String ADDRESS="";
String EMAILID="";
String GENDER="";
String CONTACTNO="";
String AGE="";
String MEMBERSHIPTYPE="";
String DATEOFJOINING="";
String EXPIRYDATE="";
String FEES="";
MEMBER_ID= rs.getString("MEMBER_ID");
FIRSTNAME= rs.getString("FIRSTNAME");
LASTNAME= rs.getString("LASTNAME");
ADDRESS = rs.getString("ADDRESS");
EMAILID = rs.getString("EMAILID");
GENDER = rs.getString("GENDER");
CONTACTNO = rs.getString("PNO");
AGE= rs.getString("AGE");
MEMBERSHIPTYPE = rs.getString("MEMBERSHIPTYPE");
DATEOFJOINING = rs.getString("JOININGDATE");
EXPIRYDATE = rs.getString("EXPIRYDATE");
FEES=rs.getString("FEES");
renew r=new renew(MEMBER_ID,FIRSTNAME,LASTNAME,ADDRESS,EMAILID,GENDER,CONTACTNO,AGE,MEMBERSHIPTYPE,DATEOFJOINING,EXPIRYDATE,FEES);
      r.setVisible(true);
      
}
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null, e);
      }
      }
  
   
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
